name: ZAP Baseline Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: windows-latest
    name: Scan the Thinking Tester Contact List website
    steps:
    - name: Checkout
      uses: actions/setup-node@v4
      with: 
        node-verdion: '20.0'

    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: 'https://thinking-tester-contact-list.herokuapp.com/'
            
